name: CI Dev Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 先把 repo checkout 下來
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 建立測試 artifact
      - name: Create test artifact
        run: |
          echo "This is a test build" > build.txt
          zip -r build.zip build.txt

      # 3️⃣ 上傳 artifact 以便後續部署使用
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # 1️⃣ 先 checkout repo，建立 .git，避免 gh release 出錯
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 下載 build job 上傳的 artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      # 3️⃣ 建立 dev release
      - name: Create Dev Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 生成唯一 tag
          TAG="dev-$(date +'%Y%m%d-%H%M%S')"
          NOTE="Automated test release for Dev environment."
          echo "Creating release with tag: $TAG"
          gh release create "$TAG" build.zip --notes "$NOTE"
