deploy-dev:
  needs: build
  runs-on: ubuntu-latest
  environment: dev
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact

    - name: Create Dev Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG="dev-$(date +'%Y%m%d-%H%M%S')"
        gh release create "$TAG" build.zip --notes "Auto release for dev"

name: CI Dev Deployment
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test artifact
        run: |
          echo "This is a test build" > build.txt
          zip -r build.zip build.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy-dev:
     needs: build
     runs-on: ubuntu-latest
     environment: dev
     steps:
       - name: Download Artifact
         uses: actions/download-artifact@v4
         with:
          name: build-artifact

       - name: Create Dev Release
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
          TAG="dev-$(date +'%Y%m%d-%H%M%S')"
          NOTE="Automated test release for Dev environment."
          echo "Creating release with tag: $TAG"
          gh release create "$TAG" build.zip --notes "$NOTE"
