name: CI/CD Deployment Pipeline

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build artifact
        run: |
          echo "This is a test build" > build.txt
          zip -r build.zip build.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  test-unit:
    needs: build
    runs-on: ubuntu-latest
    env:
      TEST_ENV: staging  # 這裡可以根據需要修改
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Run Unit Tests
        run: |
          echo "Running unit tests in $TEST_ENV environment..."
          sleep 2
          echo "✅ Unit tests passed"

  test-integration:
    needs: test-unit
    runs-on: ubuntu-latest
    env:
      TEST_ENV: staging  # 與 test-unit 可同樣設定或改為 prod
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Run Integration Tests
        run: |
          echo "Running integration tests in $TEST_ENV environment..."
          sleep 2
          echo "✅ Integration tests passed"

  deploy-staging:
    needs: test-integration
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Deploy to Staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="staging-$(date +'%Y%m%d-%H%M%S')"
          NOTE="Automated staging release after successful tests"
          gh release create "$TAG" build.zip --notes "$NOTE"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Deploy to Production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="prod-$(date +'%Y%m%d-%H%M%S')"
          NOTE="Automated production release after successful tests"
          gh release create "$TAG" build.zip --notes "$NOTE"
